server:
  port: 8088
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identify-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "wLaWr3+TMVjaUszxtX1Ib2sAjIPSW1IC5fmHmEhjFt9IX+LsYA1Ts8YMLUq5nOap"
  valid-duration: 3600 #in second
  refreshable-duration: 360000 #insecond