server:
  port: 8081
  servlet:
    context-path: /service
spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/user"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true